/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AvtalRouteImport } from './routes/avtal'
import { Route as ForhandlingarRouteImport } from './routes/forhandlingar'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MedlareRouteImport } from './routes/medlare'
import { Route as ParterRouteImport } from './routes/parter'
import { Route as PartstraffarRouteImport } from './routes/partstraffar'
import { Route as RegistreraRouteImport } from './routes/registrera'
import { Route as SokRouteImport } from './routes/sok'
import { Route as MedlingIndexRouteImport } from './routes/medling/index'
import { Route as MedlingArendeRouteImport } from './routes/medling/arende'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtalRoute = AvtalRouteImport.update({
  id: '/avtal',
  path: '/avtal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForhandlingarRoute = ForhandlingarRouteImport.update({
  id: '/forhandlingar',
  path: '/forhandlingar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MedlareRoute = MedlareRouteImport.update({
  id: '/medlare',
  path: '/medlare',
  getParentRoute: () => rootRouteImport,
} as any)
const ParterRoute = ParterRouteImport.update({
  id: '/parter',
  path: '/parter',
  getParentRoute: () => rootRouteImport,
} as any)
const PartstraffarRoute = PartstraffarRouteImport.update({
  id: '/partstraffar',
  path: '/partstraffar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistreraRoute = RegistreraRouteImport.update({
  id: '/registrera',
  path: '/registrera',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const MedlingIndexRoute = MedlingIndexRouteImport.update({
  id: '/medling/',
  path: '/medling/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedlingArendeRoute = MedlingArendeRouteImport.update({
  id: '/medling/arende',
  path: '/medling/arende',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/avtal': typeof AvtalRoute
  '/forhandlingar': typeof ForhandlingarRoute
  '/market': typeof MarketRoute
  '/medlare': typeof MedlareRoute
  '/parter': typeof ParterRoute
  '/partstraffar': typeof PartstraffarRoute
  '/registrera': typeof RegistreraRoute
  '/sok': typeof SokRoute
  '/medling/arende': typeof MedlingArendeRoute
  '/medling/': typeof MedlingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/avtal': typeof AvtalRoute
  '/forhandlingar': typeof ForhandlingarRoute
  '/market': typeof MarketRoute
  '/medlare': typeof MedlareRoute
  '/parter': typeof ParterRoute
  '/partstraffar': typeof PartstraffarRoute
  '/registrera': typeof RegistreraRoute
  '/sok': typeof SokRoute
  '/medling/arende': typeof MedlingArendeRoute
  '/medling': typeof MedlingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/avtal': typeof AvtalRoute
  '/forhandlingar': typeof ForhandlingarRoute
  '/market': typeof MarketRoute
  '/medlare': typeof MedlareRoute
  '/parter': typeof ParterRoute
  '/partstraffar': typeof PartstraffarRoute
  '/registrera': typeof RegistreraRoute
  '/sok': typeof SokRoute
  '/medling/arende': typeof MedlingArendeRoute
  '/medling/': typeof MedlingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/avtal'
    | '/forhandlingar'
    | '/market'
    | '/medlare'
    | '/parter'
    | '/partstraffar'
    | '/registrera'
    | '/sok'
    | '/medling/arende'
    | '/medling/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/avtal'
    | '/forhandlingar'
    | '/market'
    | '/medlare'
    | '/parter'
    | '/partstraffar'
    | '/registrera'
    | '/sok'
    | '/medling/arende'
    | '/medling'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/avtal'
    | '/forhandlingar'
    | '/market'
    | '/medlare'
    | '/parter'
    | '/partstraffar'
    | '/registrera'
    | '/sok'
    | '/medling/arende'
    | '/medling/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AvtalRoute: typeof AvtalRoute
  ForhandlingarRoute: typeof ForhandlingarRoute
  MarketRoute: typeof MarketRoute
  MedlareRoute: typeof MedlareRoute
  ParterRoute: typeof ParterRoute
  PartstraffarRoute: typeof PartstraffarRoute
  RegistreraRoute: typeof RegistreraRoute
  SokRoute: typeof SokRoute
  MedlingArendeRoute: typeof MedlingArendeRoute
  MedlingIndexRoute: typeof MedlingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtal': {
      id: '/avtal'
      path: '/avtal'
      fullPath: '/avtal'
      preLoaderRoute: typeof AvtalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forhandlingar': {
      id: '/forhandlingar'
      path: '/forhandlingar'
      fullPath: '/forhandlingar'
      preLoaderRoute: typeof ForhandlingarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medlare': {
      id: '/medlare'
      path: '/medlare'
      fullPath: '/medlare'
      preLoaderRoute: typeof MedlareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parter': {
      id: '/parter'
      path: '/parter'
      fullPath: '/parter'
      preLoaderRoute: typeof ParterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partstraffar': {
      id: '/partstraffar'
      path: '/partstraffar'
      fullPath: '/partstraffar'
      preLoaderRoute: typeof PartstraffarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrera': {
      id: '/registrera'
      path: '/registrera'
      fullPath: '/registrera'
      preLoaderRoute: typeof RegistreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medling/': {
      id: '/medling/'
      path: '/medling'
      fullPath: '/medling/'
      preLoaderRoute: typeof MedlingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medling/arende': {
      id: '/medling/arende'
      path: '/medling/arende'
      fullPath: '/medling/arende'
      preLoaderRoute: typeof MedlingArendeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AvtalRoute: AvtalRoute,
  ForhandlingarRoute: ForhandlingarRoute,
  MarketRoute: MarketRoute,
  MedlareRoute: MedlareRoute,
  ParterRoute: ParterRoute,
  PartstraffarRoute: PartstraffarRoute,
  RegistreraRoute: RegistreraRoute,
  SokRoute: SokRoute,
  MedlingArendeRoute: MedlingArendeRoute,
  MedlingIndexRoute: MedlingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
